version: '3'
services:
  my-golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Порт для вашего Golang приложения
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "1111:5432"  # Порт для PostgreSQL